name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Pre-accept Android SDK Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo -e "\n893704667450112217b71379d972d473970d8419\n24333f8a63717208d132635a9cc5f67a21b3693e\n504667450112217b71379d972d473970d8419\ncd50112217b71379d972d473970d8419" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "\n84449eb562853f314e6a06b12743637de96b92f" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

      - name: Build with Buildozer
        uses: ArtemSydoryk/buildozer-action@v1.2.0
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VoiceAssistant-811-APK
          path: bin/*.apk
